### ISSUE TITLE
CLI does not build

### ISSUE THREAD

**Issue by markschaake** [daniel-trinh/scalariform#109]
Instructions [in the README](https://github.com/daniel-trinh/scalariform/tree/ebb40ce6beaf9681a237393d6c1a39ca005120d8#packaging-an-executable-jar) for generating the CLI fat jar do not work due to deduplicate errors. Here's the SBT output:

```
$ sbt "project cli" "assembly"
[info] Loading global plugins from /Users/markschaake/.sbt/0.13/plugins
[info] Loading project definition from ~/forks/scalariform/project/project
[info] Loading project definition from ~/forks/scalariform/project
[info] Set current project to root (in build file:~/forks/scalariform/)
[info] Set current project to cli (in build file:~/forks/scalariform/)
[warn] No main class detected
[warn] No main class detected
[info] Including from cache: cli_2.10-0.1.8.jar
[info] Including from cache: commons-io-1.4.jar
[info] Including from cache: scalariform_2.10-0.1.8.jar
[info] Including from cache: scalariform_2.10-0.1.8.jar
[info] Including from cache: scala-library-2.10.6.jar
[info] Checking every *.class/*.jar file's SHA-1.
[info] Merging files...
[error] 2 errors were encountered during merge
java.lang.RuntimeException: deduplicate: different file contents found in the following:
~/git/forks/scalariform/cli/target/scala-2.10/cli_2.10-0.1.8.jar:META-INF/MANIFEST.MF
~/git/forks/scalariform/scalariform/target/scala-2.10/scalariform_2.10-0.1.8.jar:META-INF/MANIFEST.MF
~/git/forks/scalariform/lib_managed/jars/org.scala-lang/scala-library/scala-library-2.10.6.jar:META-INF/MANIFEST.MF
~/git/forks/scalariform/lib_managed/jars/org.scalariform/scalariform_2.10/scalariform_2.10-0.1.8.jar:META-INF/MANIFEST.MF
~/git/forks/scalariform/lib_managed/jars/commons-io/commons-io/commons-io-1.4.jar:META-INF/MANIFEST.MF
deduplicate: different file contents found in the following:
~/forks/scalariform/scalariform/target/scala-2.10/scalariform_2.10-0.1.8.jar:scalariform/BuildInfo$.class
~/forks/scalariform/lib_managed/jars/org.scalariform/scalariform_2.10/scalariform_2.10-0.1.8.jar:scalariform/BuildInfo$.class
	at sbtassembly.Assembly$.applyStrategies(Assembly.scala:140)
	at sbtassembly.Assembly$.x$1$lzycompute$1(Assembly.scala:25)
	at sbtassembly.Assembly$.x$1$1(Assembly.scala:23)
	at sbtassembly.Assembly$.stratMapping$lzycompute$1(Assembly.scala:23)
	at sbtassembly.Assembly$.stratMapping$1(Assembly.scala:23)
	at sbtassembly.Assembly$.inputs$lzycompute$1(Assembly.scala:67)
	at sbtassembly.Assembly$.inputs$1(Assembly.scala:57)
	at sbtassembly.Assembly$.apply(Assembly.scala:83)
	at sbtassembly.Assembly$$anonfun$assemblyTask$1.apply(Assembly.scala:241)
	at sbtassembly.Assembly$$anonfun$assemblyTask$1.apply(Assembly.scala:238)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (cli/*:assembly) deduplicate: different file contents found in the following:
[error] ~/forks/scalariform/cli/target/scala-2.10/cli_2.10-0.1.8.jar:META-INF/MANIFEST.MF
[error] ~/forks/scalariform/scalariform/target/scala-2.10/scalariform_2.10-0.1.8.jar:META-INF/MANIFEST.MF
[error] ~/forks/scalariform/lib_managed/jars/org.scala-lang/scala-library/scala-library-2.10.6.jar:META-INF/MANIFEST.MF
[error] ~/forks/scalariform/lib_managed/jars/org.scalariform/scalariform_2.10/scalariform_2.10-0.1.8.jar:META-INF/MANIFEST.MF
[error] ~/forks/scalariform/lib_managed/jars/commons-io/commons-io/commons-io-1.4.jar:META-INF/MANIFEST.MF
[error] deduplicate: different file contents found in the following:
[error] ~/forks/scalariform/scalariform/target/scala-2.10/scalariform_2.10-0.1.8.jar:scalariform/BuildInfo$.class
[error] ~/forks/scalariform/lib_managed/jars/org.scalariform/scalariform_2.10/scalariform_2.10-0.1.8.jar:scalariform/BuildInfo$.class
[error] Total time: 1 s, completed Feb 1, 2016 9:50:00 PM
```

**Comment by sschaef** [comment]
Please report new tickets to https://github.com/scala-ide/scalariform
